// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BillList: typeof import('./components/statistic/bill_list/BillList.vue')['default']
    BillListItem: typeof import('./components/statistic/bill_list/BillListItem.vue')['default']
    BillStatistic: typeof import('./components/statistic/BillStatistic.vue')['default']
    BmAvatar: typeof import('./components/avatar/BmAvatar.vue')['default']
    BmBar: typeof import('./components/BmBar.vue')['default']
    BmImage: typeof import('./components/img/BmImage.vue')['default']
    BmToolbarWithGoBack: typeof import('./components/toolbar/BmToolbarWithGoBack.vue')['default']
    DialogFilter: typeof import('./components/widget-wrap/DialogFilter.vue')['default']
    DialogFilterFooter: typeof import('./components/widget-wrap/DialogFilterFooter.vue')['default']
    DynamicDialogWrapper: typeof import('./components/dialog/DynamicDialogWrapper.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCardWrapper: typeof import('./components/ElCardWrapper.vue')['default']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButt: typeof import('element-plus/es')['ElRadioButt']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    MonthFilterDrawer: typeof import('./components/statistic/bill_list_filter_drawer/MonthFilterDrawer.vue')['default']
    PanelFilter: typeof import('./components/widget-wrap/PanelFilter.vue')['default']
    PrivacyStatement: typeof import('./components/login/PrivacyStatement.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollDatePicker: typeof import('./components/scroll-date-picker/ScrollDatePicker.vue')['default']
    SvgIcon: typeof import('./components/icon/SvgIcon.vue')['default']
    UserAgreement: typeof import('./components/login/UserAgreement.vue')['default']
  }
}
