
name: Deploy System

on:
  push:
    branches:
      # make sure this is the branch you are using
      - dev_filter

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # if your docs needs submodules, uncomment the following line
          # submodules: true



      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install Deps
        run: yarn install --frozen-lockfile

      - name: Build source
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          yarn run build
          > dist/.nojekyll

      - name: Deploy source
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          # This is the branch where the docs are deployed to
          repository-name: Mark-Walen/blue-bill-admin
          branch: pro_0.0
          folder: dist
